backend:
  name: github
  repo: aasrithvarma/aasrithvarma.github.io
  branch: main # Branch to update

# Media files (like images for your articles) will be saved here
media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
  - name: "articles"
    label: "Clinical Notebook Articles"
    folder: "src/content/articles" # Where new posts will be saved
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "article"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
